# Uncomment this line to define a global platform for your project
platform :ios, ‘8’

target ‘Hotmart’ do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Hotmart
    pod ‘SideMenuController’
    
end
